# Strict analysis options for MeetMind Flutter — Cris Development Standards
# Zero tolerance: no warnings, no dynamic, no implicit types

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error
    unused_element: error
    unnecessary_new: error
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_final_fields: warning
    prefer_final_locals: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Type safety — NO dynamic
    avoid_dynamic_calls: true
    avoid_returning_null_for_void: true
    type_annotate_public_apis: true
    always_declare_return_types: true
    omit_local_variable_types: false

    # Code quality
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_is_empty: true
    prefer_is_not_empty: true

    # Performance
    avoid_function_literals_in_foreach_calls: true
    prefer_collection_literals: true
    prefer_if_null_operators: true
    prefer_spread_collections: true
    unnecessary_lambdas: true

    # Documentation
    public_member_api_docs: false # Enable later when API stabilizes

    # Safety
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_statements: true
    cancel_subscriptions: true
    close_sinks: true

    # Style
    prefer_single_quotes: true
    always_put_required_named_parameters_first: true
    directives_ordering: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_this: true
    prefer_const_literals_to_create_immutables: true
